import { TeamSection } from "..";

export const year2026: TeamSection[] = [
  {
    title: "Executive Committee",
    items: [
      {
        name: "Ahmed Ayman",
        title: "Chair",
        imagePath: "",
        linkedin: "https://www.linkedin.com/in/ahmed-abouelnour/",
        region: "R8",
        section: "Egypt Section",
      },
      {
        name: "Subodha Charles",
        title: "MGA SAC Chair",
        imagePath: "",
        linkedin: "https://www.linkedin.com/in/subodha-charles/",
        region: "R10",
        section: "Sri Lanka Section",
      },
      {
        name: "Robert Sacks",
        title: "Staff Support",
        imagePath: "",
        linkedin: "https://www.linkedin.com/in/robert-sacks-9475a4310/",
        region: "R2",
        section: "Princeton-Central Jersey Section",
      },
    ],
  },
  {
    title: "Software Engineering",
    items: [
      {
        name: "Mohamed Khanfour",
        title: "Software Engineer",
        imagePath: "",
        linkedin: "https://www.linkedin.com/in/mohamedaymn/",
        region: "R8",
        section: "Egypt Section",
      },
      {
        name: "Yahya EL Adawy",
        title: "Software & Cybersecurity Engineer",
        imagePath: "",
        linkedin: "https://www.linkedin.com/in/yahyaeladawy/",
        region: "R8",
        section: "Egypt Section",
      },
      {
        name: "Yehya Mohey",
        title: "Cybersecurity Engineer",
        imagePath: "",
        linkedin: "https://www.linkedin.com/in/yehyamohey444/",
        region: "R8",
        section: "Egypt Section",
      },
      {
        name: "Menna Hany",
        title: "Cybersecurity Engineer",
        imagePath: "",
        linkedin: "https://www.linkedin.com/in/menntullah-hany-0b7627174/",
        region: "R8",
        section: "Egypt Section",
      },
    ],
  },
  {
    title: "Graphic Design",
    items: [
      {
        name: "Mohamed Zouari",
        title: "Graphic Designer",
        imagePath: "",
        linkedin: "https://www.linkedin.com/in/mohamedzouari202/",
        region: "R8",
        section: "Tunisia Section",
      },
      {
        name: "Devarsh Namboothiri",
        title: "Graphic Designer",
        imagePath: "",
        linkedin: "https://www.linkedin.com/in/devarsh-r",
        region: "R10",
        section: "Kochi Subsection",
      },
      {
        name: "Rashad Elkhudari",
        title: "Graphic Designer",
        imagePath: "",
        linkedin:
          "https://www.linkedin.com/in/rashad-alkhodary?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=ios_app",
        region: "R8",
        section: "Egypt Section",
      },
    ],
  },
  {
    title: "Content Writing",
    items: [
      {
        name: "Anoud Abdusalam",
        title: "Content Writing Lead",
        imagePath: "",
        linkedin: "https://www.linkedin.com/in/anoud-abdusalam-065aa1197/",
        region: "R8",
        section: "Palestine Subsection",
      },
      {
        name: "Melina Gonzalez",
        title: "Content Writer",
        imagePath: "",
        linkedin: "https://www.linkedin.com/in/melina-paula-gonzalez",
        region: "R9",
        section: "Argentina Section",
      },
      {
        name: "Tharusha Hemapala",
        title: "Content Writer",
        imagePath: "",
        linkedin: "https://www.linkedin.com/in/tharusha-hemapala",
        region: "R10",
        section: "Sri Lanka Section",
      },
    ],
  },
  {
    title: "Ambassadors Program",
    items: [
      {
        name: "Rakshit Jain",
        title: "Ambassador Lead",
        imagePath: "",
        linkedin: "https://www.linkedin.com/in/rakshit-a-n-jain/",
        region: "R10",
        section: "Pune Section",
      },
      {
        name: "Varghese Babu",
        title: "Ambassadors Co-Lead",
        imagePath: "",
        linkedin: "https://www.linkedin.com/in/varghese-babu",
        region: "R10",
        section: "Kerala Section",
      },
      {
        name: "Banshari Patel",
        title: "Ambassadors Co-Lead",
        imagePath: "",
        linkedin: "https://www.linkedin.com/in/banshari-patel-b699542b5/",
        region: "R10",
        section: "Gujarat Section",
      },
    ],
  },
  {
    title: "Marketing",
    items: [
      {
        name: "Lina Labidi",
        title: "Marketing Lead",
        imagePath: "",
        linkedin: "https://www.linkedin.com/in/lina-labidi9",
        region: "R8",
        section: "Tunisia Section",
      },
      {
        name: "Youmna Adel",
        title: "Marketing Specialist",
        imagePath: "",
        linkedin: "https://www.linkedin.com/in/youmna-elhoseny-9b6557253/",
        region: "R8",
        section: "Egypt Section",
      },
      {
        name: "Nagulan R",
        title: "Marketing Specialist",
        imagePath: "",
        linkedin: "https://www.linkedin.com/in/nagulan-r-566594234/",
        region: "R10",
        section: "Madras Section",
      },
      {
        name: "Bahaeddine Hammou",
        title: "Marketing Specialist",
        imagePath: "",
        linkedin: "https://www.linkedin.com/in/baha-eddine-hammou/",
        region: "R8",
        section: "Tunisia Section",
      },
    ],
  },
];
