import type { TeamSection } from "../types";

export const year2026: TeamSection[] = [
  {
    title: "Executive Committee",
    items: [
      {
        name: "Ahmed Ayman",
        title: "Chair",
        imagePath: "/images/team/2026/Ahmed-Ayman.webp",
        linkedin: "https://www.linkedin.com/in/ahmed-abouelnour/",
        region: "R8",
        section: "Egypt Section",
      },
      {
        name: "Subodha Charles",
        title: "MGA SAC Chair",
        imagePath: "/images/team/2026/Subodha-Charles.webp",
        linkedin: "https://www.linkedin.com/in/subodha-charles/",
        region: "R10",
        section: "Sri Lanka Section",
      },
      {
        name: "Robert Sacks",
        title: "Staff Support",
        imagePath: "/images/team/2026/Robert-Sacks.webp",
        linkedin: "https://www.linkedin.com/in/robert-sacks-9475a4310/",
        region: "R1",
        section: "Princeton-Central Jersey Section",
      },
    ],
  },
  {
    title: "Software Engineering",
    items: [
      {
        name: "Mohamed Khanfour",
        title: "Software Engineer",
        imagePath: "/images/team/2026/Mohamed-Khanfour.webp",
        linkedin: "https://www.linkedin.com/in/mohamedaymn/",
        region: "R8",
        section: "Egypt Section",
      },
      {
        name: "Yahya EL Adawy",
        title: "Software & Cybersecurity Engineer",
        imagePath: "/images/team/2026/Yahya-EL-Adawy.webp",
        linkedin: "https://www.linkedin.com/in/yahyaeladawy/",
        region: "R8",
        section: "Egypt Section",
      },
      {
        name: "Yehya Mohey",
        title: "Cybersecurity Engineer",
        imagePath: "/images/team/2026/Yehya-Mohey.webp",
        linkedin: "https://www.linkedin.com/in/yehyamohey444/",
        region: "R8",
        section: "Egypt Section",
      },
      {
        name: "Menna Hany",
        title: "Cybersecurity Engineer",
        imagePath: "/images/team/2026/Menna-Hany.webp",
        linkedin: "https://www.linkedin.com/in/menntullah-hany-0b7627174/",
        region: "R8",
        section: "Egypt Section",
      },
    ],
  },
  {
    title: "Content Writing",
    items: [
      {
        name: "Anoud Abdusalam",
        title: "Content Writing Lead",
        imagePath: "/images/team/2026/Anoud-Abdusalam.webp",
        linkedin: "https://www.linkedin.com/in/anoud-abdusalam-065aa1197/",
        region: "R8",
        section: "Palestine Subsection",
      },
      {
        name: "Melina Gonzalez",
        title: "Content Writer",
        imagePath: "/images/team/2026/Melina-Gonzalez.webp",
        linkedin: "https://www.linkedin.com/in/melina-paula-gonzalez/",
        region: "R9",
        section: "Argentina Section",
      },
      {
        name: "Tharusha Hemapala",
        title: "Content Writer",
        imagePath: "/images/team/2026/Tharusha-Hemapala.webp",
        linkedin: "https://www.linkedin.com/in/tharusha-hemapala/",
        region: "R10",
        section: "Sri Lanka Section",
      },
    ],
  },
  {
    title: "Ambassadors Program",
    items: [
      {
        name: "Rakshit Jain",
        title: "Ambassadors Lead",
        imagePath: "/images/team/2026/Rakshit-Jain.webp",
        linkedin: "https://www.linkedin.com/in/rakshit-a-n-jain/",
        region: "R10",
        section: "Pune Section",
      },
      {
        name: "Varghese Babu",
        title: "Ambassadors Co-Lead",
        imagePath: "/images/team/2026/Varghese-Babu.webp",
        linkedin: "https://www.linkedin.com/in/varghese-babu",
        region: "R10",
        section: "Kerala Section",
      },
      {
        name: "Qusai Mashriqi",
        title: "R8 Ambassadors Lead",
        imagePath: "/images/team/2026/Qusai-Mashriqi.webp",
        linkedin: "https://www.linkedin.com/in/qusai-mashriqi/",
        region: "R8",
        section: "Jordan Section",
      },
      {
        name: "Camila Castanha",
        title: "R9 Ambassadors Lead",
        imagePath: "/images/team/2026/Camila-Castanha.webp",
        linkedin: "https://www.linkedin.com/in/camila-porto-belli-728064329/",
        region: "R9",
        section: "Minas Gerais Section",
      },
      // {
      //   name: "Banshari Patel",
      //   title: "Ambassadors Co-Lead",
      //   imagePath: "/images/team/2026/Banshari-Patel.webp",
      //   linkedin: "https://www.linkedin.com/in/banshari-patel-b699542b5/",
      //   region: "R10",
      //   section: "Gujarat Section",
      // },
    ],
  },
  {
    title: "Marketing",
    items: [
      {
        name: "Lina Labidi",
        title: "Marketing Lead",
        imagePath: "/images/team/2026/Lina-Labidi.webp",
        linkedin: "https://www.linkedin.com/in/lina-labidi9",
        region: "R8",
        section: "Tunisia Section",
      },
      {
        name: "Vildana Hrnjić",
        title: "Brand Designer",
        imagePath: "/images/team/2026/Vildana-Hrnjić.webp",
        linkedin: "https://www.linkedin.com/in/vildana-hrnji%C4%87/",
        region: "R8",
        section: "Bosnia and Herzegovina Section",
      },
      {
        name: "Rayen Dellai",
        title: "Graphic Designer",
        imagePath: "/images/team/2026/Rayen-Dellai.webp",
        linkedin: "http://www.linkedin.com/in/rayen-dellai-9688a4261",
        region: "R8",
        section: "Tunisia Section",
      },
      {
        name: "Mohamed Zouari",
        title: "Graphic Designer",
        imagePath: "/images/team/2026/Mohamed-Zouari.webp",
        linkedin: "https://www.linkedin.com/in/mohamedzouari202/",
        region: "R8",
        section: "Tunisia Section",
      },
      {
        name: "Devarsh Namboothiri",
        title: "Graphic Designer",
        imagePath: "/images/team/2026/Devarsh-Namboothiri.webp",
        linkedin: "https://www.linkedin.com/in/devarsh-r/",
        region: "R10",
        section: "Kochi Subsection",
      },
      {
        name: "Rashad Elkhudari",
        title: "Graphic Designer",
        imagePath: "/images/team/2026/Rashad-Elkhudari.webp",
        linkedin:
          "https://www.linkedin.com/in/rashad-alkhodary?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=ios_app",
        region: "R8",
        section: "Egypt Section",
      },
      {
        name: "Youmna Adel",
        title: "Marketing Specialist",
        imagePath: "/images/team/2026/Youmna-Adel.webp",
        linkedin: "https://www.linkedin.com/in/youmna-elhoseny-9b6557253/",
        region: "R8",
        section: "Egypt Section",
      },
      {
        name: "Nagulan R",
        title: "Marketing Specialist",
        imagePath: "/images/team/2026/Nagulan-R.webp",
        linkedin: "https://www.linkedin.com/in/nagulan-r-566594234/",
        region: "R10",
        section: "Madras Section",
      },
      {
        name: "Bahaeddine Hammou",
        title: "Marketing Specialist",
        imagePath: "/images/team/2026/Bahaeddine-Hammou.webp",
        linkedin: "https://www.linkedin.com/in/baha-eddine-hammou/",
        region: "R8",
        section: "Tunisia Section",
      },
    ],
  },
];
